# Generated by Django 3.2.1 on 2021-05-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='api_images/')),
                ('profile_pic', models.ImageField(upload_to='api_images/propic/')),
            ],
        ),
    ]
