# Generated by Django 3.2.1 on 2021-05-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
