# Generated by Django 3.2.1 on 2021-05-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
