# Generated by Django 3.2.1 on 2021-05-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_owner_tst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tst',
        ),
    ]
