# Generated by Django 3.2.1 on 2021-05-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('img_link1', models.CharField(max_length=300)),
                ('img_link2', models.CharField(max_length=300)),
                ('img_link3', models.CharField(max_length=300)),
                ('img_link4', models.CharField(max_length=300)),
                ('img_link5', models.CharField(max_length=300)),
                ('img_link6', models.CharField(max_length=300)),
                ('img_link7', models.CharField(max_length=300)),
                ('img_link8', models.CharField(max_length=300)),
                ('img_link9', models.CharField(max_length=300)),
                ('img_link10', models.CharField(max_length=300)),
                ('img_link11', models.CharField(max_length=300)),
                ('img_link12', models.CharField(max_length=300)),
                ('img_link13', models.CharField(max_length=300)),
                ('img_link14', models.CharField(max_length=300)),
                ('img_link15', models.CharField(max_length=300)),
                ('img_link16', models.CharField(max_length=300)),
                ('img_link17', models.CharField(max_length=300)),
                ('img_link18', models.CharField(max_length=300)),
                ('img_link19', models.CharField(max_length=300)),
                ('img_link29', models.CharField(max_length=300)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
