# Generated by Django 3.2.1 on 2021-06-28 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedName', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('imgUrl', models.TextField()),
                ('count', models.IntegerField()),
                ('likedCount', models.IntegerField()),
                ('isLiked', models.BooleanField(verbose_name=False)),
                ('price', models.IntegerField()),
                ('offers', models.DecimalField(decimal_places=2, max_digits=3)),
                ('vendorName', models.CharField(max_length=20)),
                ('typeOf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.typeof')),
            ],
        ),
    ]
