# Generated by Django 3.2.1 on 2021-06-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuckk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdkfl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='what',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsdf', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='slkdfj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='images.fuckk'),
        ),
    ]
