# Generated by Django 3.2.1 on 2021-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sya',
            field=models.IntegerField(null=True),
        ),
    ]
