# Generated by Django 3.2.1 on 2021-05-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_link29',
            new_name='img_link20',
        ),
    ]
