# Generated by Django 3.2.1 on 2021-06-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210630_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='what',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='slkdfj',
        ),
        migrations.DeleteModel(
            name='fuckk',
        ),
    ]
