# Generated by Django 3.2.1 on 2021-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_img_link29_image_img_link20'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuppyNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
