# Generated by Django 3.2.1 on 2021-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_animal_sya'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sdjfh',
            field=models.IntegerField(null=True),
        ),
    ]
