# Generated by Django 3.2.1 on 2021-06-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210628_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='liked',
            new_name='isLiked',
        ),
    ]
