# Generated by Django 3.2.1 on 2021-06-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210630_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imgUrl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='isLiked',
            field=models.BooleanField(null=True, verbose_name=False),
        ),
        migrations.AlterField(
            model_name='animal',
            name='likedCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nameOfVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.vendorname'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='offers',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='typeOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.typeof'),
        ),
    ]
