# Generated by Django 3.2.1 on 2021-07-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_animal_sdjfh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='sdjfh',
            new_name='sdh',
        ),
    ]
