# Generated by Django 3.2.1 on 2021-07-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20210630_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nameOfVendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='images.vendorname'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='typeOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theOne', to='images.typeof'),
        ),
    ]
