# Generated by Django 3.2.1 on 2021-07-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_sdjfh_animal_sdh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='sdh',
            new_name='sdhsd',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='sya',
            new_name='syaqas',
        ),
    ]
