# Generated by Django 3.2.1 on 2021-06-29 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_animal_testcatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='sd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='tt',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.sd'),
        ),
    ]
