# Generated by Django 3.2.1 on 2021-06-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210629_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='what',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='testCatch',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='tt',
        ),
        migrations.DeleteModel(
            name='Catch',
        ),
        migrations.DeleteModel(
            name='sd',
        ),
    ]
