# Generated by Django 3.2.1 on 2021-07-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210703_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='sdhsd',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='syaqas',
        ),
    ]
