# Generated by Django 3.2.1 on 2021-07-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_animal_nameofvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorname',
            name='typeOfVendorRef',
            field=models.ManyToManyField(related_name='typeOfvendorReference', to='images.TypeOf'),
        ),
    ]
