# Generated by Django 3.2.1 on 2021-06-29 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20210629_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='sdk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='sdd',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.sdk'),
        ),
    ]
