# Generated by Django 3.2.1 on 2021-07-02 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_vendorname_typeofvendorref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='typeOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeOf', to='images.typeof'),
        ),
    ]
