# Generated by Django 3.2.1 on 2021-07-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20210703_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='df',
        ),
    ]
