# Generated by Django 3.2.1 on 2021-06-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_anys'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='a',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.anys'),
        ),
    ]
