# Generated by Django 3.2.1 on 2021-07-02 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_animal_typeof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='nameOfVendor',
        ),
        migrations.AddField(
            model_name='vendorname',
            name='animalOne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animalOne', to='images.animal'),
        ),
    ]
