# Generated by Django 3.2.1 on 2021-06-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_animal_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='a',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sdd',
        ),
        migrations.DeleteModel(
            name='anys',
        ),
        migrations.DeleteModel(
            name='sdk',
        ),
    ]
