# Generated by Django 3.2.1 on 2021-07-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_remove_vendorname_typeofvendorref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorname',
            name='animalOne',
        ),
        migrations.AddField(
            model_name='animal',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='images.vendorname'),
        ),
    ]
