# Generated by Django 3.2.1 on 2021-07-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_rename_name_vendorname_vname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorname',
            old_name='vname',
            new_name='name',
        ),
    ]
