# Generated by Django 3.2.1 on 2021-07-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_rename_vname_vendorname_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='likedCount',
            new_name='total_liked',
        ),
    ]
