# Generated by Django 3.2.1 on 2021-07-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_rename_likedcount_animal_total_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='likedCount',
            field=models.IntegerField(null=True),
        ),
    ]
