# Generated by Django 3.2.1 on 2021-07-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_rename_isliked_animal_islikedd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='isLikedd',
            new_name='a',
        ),
        migrations.AddField(
            model_name='animal',
            name='isLiked',
            field=models.BooleanField(default=True),
        ),
    ]
