# Generated by Django 3.2.1 on 2021-07-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_animal_likedcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='likedCount',
        ),
    ]
