# Generated by Django 3.2.1 on 2021-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20210703_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='a',
        ),
        migrations.AlterField(
            model_name='animal',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
