# Generated by Django 3.2.1 on 2021-07-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_auto_20210703_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='f',
            field=models.CharField(default='NHone', max_length=3),
        ),
    ]
