# Generated by Django 3.2.1 on 2021-07-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_animal_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='f',
            field=models.BooleanField(default=True),
        ),
    ]
