# Generated by Django 3.2.1 on 2021-07-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_rename_total_liked_animal_total_likd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='total_likd',
            new_name='total_liked',
        ),
    ]
