# Generated by Django 3.2.1 on 2021-07-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_alter_animal_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='f',
        ),
    ]
