# Generated by Django 3.2.1 on 2021-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_remove_animal_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sdlfj',
            field=models.IntegerField(null=True),
        ),
    ]
