# Generated by Django 3.2.1 on 2021-07-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_animal_sdlfj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='isLiked',
            new_name='isLikeds',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='sdlfj',
        ),
    ]
