# Generated by Django 3.2.1 on 2021-07-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_animal_isliked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='isLikeds',
        ),
    ]
