# Generated by Django 3.2.1 on 2021-07-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_remove_animal_islikeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorname',
            name='avatar',
            field=models.TextField(null=True),
        ),
    ]
