# Generated by Django 3.2.1 on 2021-07-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_vendorname_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
