# Generated by Django 3.2.1 on 2021-07-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0025_animal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='description',
        ),
    ]
