# Generated by Django 3.2.1 on 2021-07-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0026_remove_animal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
