# Generated by Django 3.2.1 on 2021-07-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0027_animal_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='description',
            new_name='descriptions',
        ),
    ]
